### ISSUE TITLE
Support wildcard "include EVERYTHING" and "include NOTHING" for Projection clause

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#1001]
Due to planned changes for auto-exclusion of certain pseudo-virtual fields (namely, `$vector`), we need mechanism to allow specifying "include everything", like so:

```
{"projection": {
	"*" : 1
}}
```

and for symmetry, might as well add its counterpart:

```
{"projection": {
	"*" : 0
}}
```

for "include nothing".

In both cases this would affect all fields stored in underlying `"doc_json"` as well as otherwise special key property, `"_id"`.

**Comment by vkarpov15** [comment]
I checked and no problems with "*" as a projection field in mongoose

However, I wanted to propose a couple of alternative syntaxes:

1. Similar to `includeSimilarity` option, add `includeVector` or `include$Vector` option
2. Mongoose supports prefixing a field with `+` to include automatically excluded fields without excluding other fields. So `{ projection: { '+$vector': 1 } }` would include `$vector` without excluding other fields
3. [MongoDB's `$meta` syntax](https://www.mongodb.com/docs/v4.2/reference/operator/projection/meta/), which similarly includes fields that are projected out by default without projecting others in. So `{ projection: { $vector: { $meta: '$vector' } } }` or something similar

**Comment by vkarpov15** [comment]
I checked and no problems with "*" as a projection field in mongoose

However, I wanted to propose a couple of alternative syntaxes:

1. Similar to `includeSimilarity` option, add `includeVector` or `include$Vector` option
2. Mongoose supports prefixing a field with `+` to include automatically excluded fields without excluding other fields. So `{ projection: { '+$vector': 1 } }` would include `$vector` without excluding other fields
3. [MongoDB's `$meta` syntax](https://www.mongodb.com/docs/v4.2/reference/operator/projection/meta/), which similarly includes fields that are projected out by default without projecting others in. So `{ projection: { $vector: { $meta: '$vector' } } }` or something similar

**Comment by tatu-at-datastax** [comment]
Thank you @vkarpov15 for pointing out these alternatives.

I realize that this issue is somewhat vague because lacking of the bigger sister-issue (which I should create; we only have internal Jira for it so far): for context, we specifically want to change handling of `$vector` (and near future `$vectorize`) data properties.

With that, of suggestions:

1. I think `includeSimilarity` is quite difference since it adds something that is not in the Document itself, unlike `$vector` or `$vectorize` which are provided as part of document (`doc_json`), or added to it via vectorization
2. We need this feature for all clients, so Mongoose-specific functionality is probably not enough to support use cases
3. `$meta` includes query-produced/specific metadata, similar to (1), and similarly different from what we try to do here.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 created #1005 for the bigger issue that this is supporting.

**Comment by vkarpov15** [comment]
For (2), I meant supporting +$vector as a projection key on the data-api side, not just in stargate-mongoose.

My concern with the wildcard projection is 2-fold: 1) can never support fields named *, 2) no way to include $vector without including $vectorize, unless we support { *: 1, $vectorize: 0 } or something similar

**Comment by tatu-at-datastax** [comment]
We do not allow fields named `*`: it's not an allowed character, so for Data API this is not a problem (I don't see a need to start allowing such name, our name validity rules are quite strict).

As to inclusion of `$vector` vs `$vectorize`, we do support regular inclusion -- this is just a short-cut, not the only way to include them. So it is possible to include just one or the other, using "regular"

    `$vectorize`: 1

notation. Although true enough, usage can get cumbersome.

**Comment by vkarpov15** [comment]
That's fair.

Another option: what do you think about treating `{ $vector: 1 }` as a non-exclusive projection by default? Like how `{ prop: 1, _id: 0 }` is allowed as a way to override `_id` being included by default, maybe we add `{ $vector: 1, prop: 0 }` as a way to override $vector being excluded by default.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 yes, that is the plan roughly speaking (as per #1005). So this option is only for very specific use case, by frontend/dataloader, to have stable Projection that will always include everything -- unlike soon changing default/no-projection which will hide `$vector` (and, as per current plans `$vectorize`).
