### ISSUE TITLE
Data API logs are not collected in github integration-tests

### ISSUE THREAD

**Issue by Yuqi-Du** [stargate/data-api#1034]
The integration tests print out logging for the db infrastructure (coordinator and cassandra nodes) but not for the Data API itself. It would be helpful to have this enabled for debugging purposes.

**Comment by jeffreyscarpenter** [comment]
The desired behavior is actually not supported by Quarkus/Testcontainers. If you really need to see the logs for a given test the options are:

- run the test locally with Data API as a docker container, and either monitor the logs using the Docker UI or command line. Starting the API container external to the test is a good way to make sure the logs persist. This is described in the README.
- run the test with Data API in dev mode - not as docker container.
