### ISSUE TITLE
Misleading error message about projection having $fields

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1038]
Considering that

```# These projections:
    projection={"$uuid": True}
    projection={"$objectId": True}
    projection={"$similarity": True}
    projection={"$argyroneta": True}  # i.e. arbitrary $something...

# yield the error:
    {
        "errors": [
            {
                "errorCode": "UNSUPPORTED_PROJECTION_PARAM",
                "message": "Unsupported projection parameter: path cannot start with '$' (no root-level operators)"
            }
        ]
    }
```

but

```
# These work as intended:
    projection={"$vector": True}
    projection={"$vectorize": True}
```

my point is that the text of the error message is a bit misleading. I suggest it should say something to the effect of,

> Unsupported projection parameter: `$vector[/ize]` are the only allowed path that can start with `$`

or something similar to convey the idea that yes, actual fields from the document which start with $ are projectable.

====

[Tatu]:

Agreed... it is bit tricky because `$` is overloaded for us now in some ways: usually it means operator. But sometimes like as with Projection there are "special" fields.

but I agree that error is misleading. So [...] **we can change wording, leaving error code as is**

([source](https://datastax.slack.com/archives/C05PTSGBYL9/p1713444202915699))

**Comment by vkarpov15** [comment]
I agree this error message could be better, and indicating that only $vector and $vectorize are supported top-level projections that start with $ would be better. We would just need to be careful about other $ keys if/when we add them.

A related note: what about fields that start with _ other than _id, should we make a similar change for those? If I remember correctly, _id is the only field that we allow that starts with _, or is that not a concern since _ isn't used to prefix operators?

**Comment by tatu-at-datastax** [comment]
Quick note: I don't think we intentionally block fields starting with `_`. If we do, it's probably due to regex by accident only allowing letters as the first char (but I am not 100% sure).

**Comment by vkarpov15** [comment]
@tatu-at-datastax I checked and I can save a document with a field named `_test`, so it is likely worth considering how we handle fields that start with `_`.

**Comment by tatu-at-datastax** [comment]
Yeah I don't think we have any special handling wrt leading underscore, unlike for `$` (which is only allowed for operators and specific non-standard fields).
Given this, I don't think we have need or desire to impose specific limit at this point: such fields/properties may already be in use by customers.
