### ISSUE TITLE
projection {"$vector": 1} does not project out the other fields anymore

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1106]
Startig with 1.0.7 (more or less), the `projection={"$vector": 1}` has the effect that the whole document is returned, and not just `$vector` and `_id` as it used to be. This is a breaking change that is now in production.

The reason is that with the preparations for the exclude-$vector-by-default, this is now treated as a special field and does not undergo the same projection logic as 'ordinary' fields.

Still, it is somewhat counterintuitive and a sudden change in the API behaviour w.r.t. previous versions. This issue is to capture this finding for a future discussion (along with the rest of the exclude-$vector/ize-by-default themes).

[related thread](https://datastax.slack.com/archives/C05PTSGBYL9/p1716282820359239)

**Comment by tatu-at-datastax** [comment]
With #1037, planned for inclusion in v1.0.10, defaults will change wrt inclusion of `$vector` and `$vectorize`, and the current thinking is that behavior mentioned here is the one will keep. So while the change pre-1.0.10 is unfortunate (unplanned), there is no benefit from trying to revert it.

Keeping the issue open until v1.0.10 release, just in case.
