### ISSUE TITLE
$vectorize: Misleading error when `authentication.providerKey` not set

### ISSUE THREAD

**Issue by vkarpov15** [stargate/data-api#1124]
Suppose you create a collection without an `authentication.providerKey`:

```
{
    vector: {
      dimension: 1536,
      metric: 'cosine',
      service: {
        provider: 'openai',
        modelName: 'text-embedding-ada-002'
      }
    }
  }
```

If you try to use `$vectorize` with this new collection:

```
{
  "insertOne": {
    "document": {
      "title": "foo",
      "$vectorize": "taco tuesday"
    }
  }
}
```

You get an NPE: `[{"message":"java.lang.NullPointerException: Param was null","errorCode":"SERVER_UNHANDLED_ERROR"}]` similar to #1116.

The error message should be better. Ideally throw an error when calling `createCollection()`, but ideally a more helpful error that there's missing credentials like `VECTORIZE_CREDENTIAL_INVALID` would be good

**Comment by Yuqi-Du** [comment]
Thanks, Val
New error will be like this when you do insertOne, but collection does not have the `authentication.providerKey`
```
{
    "errors": [
        {
            "message": "Embedding Gateway failed to process request: getCredential error, integration credential is null",
            "errorCode": "EMBEDDING_GATEWAY_PROCESSING_ERROR"
        }
    ]
}
```

**Comment by Yuqi-Du** [comment]
@Hazel-Datastax 
Correct me if I am wrong.
```
{
    vector: {
      dimension: 1536,
      metric: 'cosine',
      service: {
        provider: 'openai',
        modelName: 'text-embedding-ada-002'
      }
    }
  }
```
This basically says this collection will use header-based vectorize authentication. Correct?
So we should not error out for createCollection.

**Comment by Hazel-Datastax** [comment]
> @Hazel-Datastax Correct me if I am wrong.
> 
> ```
> {
>     vector: {
>       dimension: 1536,
>       metric: 'cosine',
>       service: {
>         provider: 'openai',
>         modelName: 'text-embedding-ada-002'
>       }
>     }
>   }
> ```
> 
> This basically says this collection will use header-based vectorize authentication. Correct? So we should not error out for createCollection.

Correct. It expects either "header-based" or "none"

**Comment by vkarpov15** [comment]
I think "Embedding Gateway failed to process request: getCredential error, integration credential is null" error on `insertOne()` is sufficient for this case. The NPE was very confusing, this error message is much better.

**Comment by vkarpov15** [comment]
Just one small follow-up question: is there a way to get `$vectorize` to work correctly if you've created a collection using the following?

```
{
    vector: {
      dimension: 1536,
      metric: 'cosine',
      service: {
        provider: 'openai',
        modelName: 'text-embedding-ada-002'
      }
    }
  }
``` 

If not, we should consider making `createCollection()` fail in this case, maybe just based on the `provider`?
