### ISSUE TITLE
docker-compose changes to consider

### ISSUE THREAD

**Issue by polandll** [stargate/data-api#1158]
(1) Consider hard-coding the DSETAG and HCDTAG, rather than using mvnw. Not everyone has maven installed, and after I tried to copy your scripts to my own repo, I discovered they depended on mvnw in the repo where these docker-compose scripts reside.

(2) Consider using two variables, stdport and fwdport. Why? If you are running more than one docker-compose with different DSE/HCD/C* versions, you will have clashes. I do this:

```
export std_port=9042
export fwd_port=9035
```

and map the fwd_port to different values to avoid conflict.

(3) I've added some logic to start 1,2, or 3 nodes in my start script. I generally only need 1 node, but sometimes need 3. This logic is not the prettiest, but it allows me to decide on startup:

```
export node_name_1='backend-dse69-1'
export node_name_2='backend-dse69-2'
export node_name_3='backend-dse69-3'

if [ "$num_nodes" -eq 1 ]; then
    # Make sure node_name_1, the seed node, is up before bringing up other nodes and stargate
    docker compose up -d ${node_name_1}
    # Wait until the seed node is up before bringing up more nodes
    (docker compose logs -f ${node_name_1} &) | grep -q "Created default superuser role"
    echo "Only one node requested, ${node_name_1} is up and running."
elif [ "$num_nodes" -eq 2 ]; then
    docker compose up -d ${node_name_1}
    (docker compose logs -f ${node_name_1} &) | grep -q "Created default superuser role"
    docker compose up -d ${node_name_2}
    (docker compose logs -f ${node_name_2} &) | grep -q "is now part of the cluster"
    echo "Two nodes requested, ${node_name_1} and ${node_name_2} are up and running."
elif [ "$num_nodes" -eq 3 ]; then
    docker compose up  -d ${node_name_1}
    (docker compose logs -f ${node_name_1} &) | grep -q "Created default superuser role"
    docker compose up  -d ${node_name_2}
    (docker compose logs -f ${node_name_2} &) | grep -q "is now part of the cluster"
    docker compose up  -d ${node_name_3}
    (docker compose logs -f ${node_name_3} &) | grep -q "is now part of the cluster"
    echo "Three nodes requested, ${node_name_1}, ${node_name_2}, and ${node_name_3} are up and running."
```

**Comment by maheshrajamani** [comment]
@polandll In your multinode configuration, how is the seed node detail provided to the node 2 and 3?

**Comment by polandll** [comment]
I just assign the first node as the seed for all of them. I use:
- SEEDS=backend-dse69-1
and backend-dse69-1 is the name of the first node.
