### ISSUE TITLE
Log error codes and messages 

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/data-api#1197]
Anytime we return an error code in response to a user request, we should also log it. The log message should contain the standard mdc content (tenant id, namespace, collection) and the error code and error message.

**Comment by tatu-at-datastax** [comment]
Quick note: to avoid spamming logs, should log at INFO level or DEBUG -- specifically not as ERROR in case where we don't have internal processing problem (uncaught/unmappable exception).
