### ISSUE TITLE
Remove use of `io.stargate:sgv2-api-parent` parent pom by Data API

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#1341]
Once other dependencies to Stargate have been removed, we should finally remove use of Stargate v2(.1) parent pom, `sgv2-api-parent`. This will probably require some copy-pasting, but finally removes all dependency to Stargate artifacts (parent pom still needs to be resolved, read, as of now).

**Comment by jeffreyscarpenter** [comment]
closed by #1351
