### ISSUE TITLE
Add new keyspace commands, deprecate namespace commands

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/data-api#1376]
As described in #1373:

Add keyspace operations to the API to parallel the namespace operations, and mark the namespace operations as deprecated.
- FindNamespaces -> FindKeyspaces
- CreateNamespace → CreateKeyspace
- DropNamespace → DropKeyspace
- Return a warning message in the response of the keyspace operations that indicates use of a deprecated command.
- One way to do this in code: rename existing operations to their new names, add operations with the old names, marked as deprecated, which act as aliases to the new operations.
- Make sure all metrics/logging reference new operation names. We do not want to capture metrics/logging for the old operation names.
- Make sure swagger/OpenAPI marks old operation names as deprecated.

**Comment by Yuqi-Du** [comment]
Note, 
What differs to the original ticket is that **we decide to keep the deprecated commands metrics and logs** . So, two different metrics and logs even these commands are the 'same'.

E.G. createNamespaceCommand, createKeyspaceCommand.
e,g.

command_processor_process_seconds_count{command="CreateKeyspaceCommand",error="false",error_class="NA",error_code="NA",module="sgv2-jsonapi",sort_type="NONE",tenant="unknown",vector_enabled="false",} 1.0

command_processor_process_seconds_count{command="CreateNamespaceCommand",error="false",error_class="NA",error_code="NA",module="sgv2-jsonapi",sort_type="NONE",tenant="unknown",vector_enabled="false",} 1.0

**Comment by Yuqi-Du** [comment]
Regarding warning msg, here is the example:

{
    "status": {
        "namespaces": [
            "system_auth",
            "system_schema",
        ]
        "warnings": ["warning 1", "warning 2"]
    }
}
the change is, we add a command status key called warnings that is a list / json array of strings. Include the deprecation notice in that, and we can re-use this status field with API Tables to warn about missing indexes.

**Comment by jeffreyscarpenter** [comment]
@Yuqi-Du can we close this issue now since the linked PR is merged?
