### ISSUE TITLE
Data API JsonCodec impl: date/time values (date, duration, time, timestamp)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#1385]
Add

* Unit tests for 4 supported (to some degree) CQL data types: `date`, `duration`, `time`, `timestamp` (`timeuuid` not time-related in same way)
* Integration tests for creating tables with all types, insert, find (unless already existing).

**Comment by vkarpov15** [comment]
What will the syntax look like? $date, $duration, $time, etc.?

**Comment by tatu-at-datastax** [comment]
No, basic JSON Strings. Aaron has a document that details plans but so far "blob" (binary) type is the only one for Tables that uses EJSON wrapper.
Tables has the benefit that we (must) have CQL Schema available at time of conversion to know CQL Type to convert to/from.

So:

1. "date":  `"2024-09-24"`
2. "duration":  `"1h30m"` OR `"PT1H30M"`
3. "time": `"12:34:56.789"`
4. "timestamp": `"2024-09-12T10:15:30Z"`
