### ISSUE TITLE
createTable command with `_id` errors out

### ISSUE THREAD

**Issue by vkarpov15** [stargate/data-api#1396]
The following createTable() command:

```
{
  "createTable": {
    "name": "bots",
    "definition": {
      "primaryKey": "_id",
      "columns": {
        "_id": {
          "type": "text"
        },
        "name": {
          "type": "text"
        }
      }
    }
  }
}

```

throws the following error:

```
[{"message":"Server failed: root cause: (java.lang.IllegalArgumentException) Invalid CQL form [_id]: needs double quotes","errorCode":"SERVER_UNHANDLED_ERROR"}
```

Looks like we also need some double quotes for createTable?

**Comment by tatu-at-datastax** [comment]
@vkarpov15 yes, thank you for reporting this!

**Comment by tatu-at-datastax** [comment]
@vkarpov15 Cannot reproduce, see #1401 for attempted reproduction: table creation succeeds.

**Comment by vkarpov15** [comment]
I confirmed this was due to an out-of-date version of Data API. `createTable` works fine on my end now.

**Comment by tatu-at-datastax** [comment]
Thank you for confirming @vkarpov15.
