### ISSUE TITLE
incorporate warning message into new API exception design.

### ISSUE THREAD

**Issue by Yuqi-Du** [stargate/data-api#1406]
we added a command status key called warnings that is a list / json array of strings. Include the deprecation notice in that, and we can re-use this status field with API Tables to warn about missing indexes.

we need to generate the message by using the new APIExceptions code so we can template the message. Use a new "WARNING" family, no scope, create the APIException and use the body / message .

**Comment by amorton** [comment]
Note: looking at #1397 there may be a more general case for just "message templating". For example, the deprecation message for createNamespace. 

We may want to say "The command findNamespace has been deprecated and will be removed in future releases..." to begin with, then when we have an actual date / versio change it to have the correct date.  

So we have a decision: 

1) Create WARNING and/or MESSAGE  exception family, they will both have direct sub classes of the ApiException, they do not need to have a scope, they just have codes and use all the error templating. We then create instances the same way, and just get the body / message.

2) we do some re-work and extract warning and message templating seperated from the APIException. 

Current thought is we have spent a lot of time on ApiExceptions and investing more time on plumbing is not the needed now. If we go forward with option 1) it will be reasonably clean to come back later on and refactor if we want to.
