### ISSUE TITLE
Issue with `COLLECTION_NOT_EXIST` error w/ Errors v2

### ISSUE THREAD

**Issue by toptobes** [stargate/data-api#1531]
When performing an operation on a nonexistent error on `v1.0.17` in dev, getting the following response from the server:
```
{
  errors: [
    {
      message: 'non_existent_collection',
      errorCode: 'COLLECTION_NOT_EXIST',
      id: '3b0dcaec-d46f-43b0-bc4c-ad9425595c44',
      family: 'REQUEST',
      title: 'Collection does not exist, collection name',
      scope: 'EMPTY'
    }
  ]
}
```

The `title` is expected to actually be of the following format, with a trailing colon & the collection name:
```
Collection does not exist, collection name: [COLLECTION NAME]
```

Beyond, due to unfortunate decisions in the TS client in its early stages, it actually attempts to parse the collection name from the `message` field, expecting an error message of the format `.*:(.*?)`, e.g. `'Collection does not exist, collection name: [COLLECTION NAME]'`, to extract the collection name.

It's not strictly necessary to have the message be of this format, but it'd be detrimental to the TS client in that the `CollectionNotFoundError.collectionName` field will be permanently `undefined` as it would no longer parse the error message correctly (since atm it's just `'non_existent_collection'`).

It shouldn't be a huge issue however, given that it will be fixed in future client versions, and it's likely not the most common error. However, it would be nice if the message would abide to that format for the time being.

**Comment by amorton** [comment]
thanks, can you pls provide the command you sent.

**Comment by toptobes** [comment]
```
CommandStartedEvent {
  command: { insertOne: { document: { username: 'test' } } },
  keyspace: 'default_keyspace',
  collection: 'non_existent_collection',
  commandName: 'insertOne',
  url: 'https://44f5ad1d-4724-40e3-8bdf-5924f6e75481-us-west-2.apps.astra-dev.datastax.com/api/json/v1/default_keyspace/non_existent_collection',
  timeout: 60000
}
```

**Comment by tatu-at-datastax** [comment]
@amorton This is the issue we discussed on Slack.

**Comment by tatu-at-datastax** [comment]
As can be seen from https://github.com/stargate/data-api/actions/runs/11330530094/job/31508553734?pr=1536 lots of unit tests fail:

```
Error:  Tests run: 2186, Failures: 130, Errors: 0, Skipped: 0
```

when ErrorsV2 enabled and similarly many ITs:

```
Error:  Tests run: 748, Failures: 94, Errors: 0, Skipped: 2
```

Will now revert message generation change to resolve these.

**Comment by tatu-at-datastax** [comment]
PR for resolving the issue #1536

**Comment by tatu-at-datastax** [comment]
#1536 is ready, will discuss with team, get reviews & need to decide how to proceed.
