### ISSUE TITLE
Confirm sparse data is returned for table reads

### ISSUE THREAD

**Issue by amorton** [stargate/data-api#1571]
The design says that for rows in a table we return sparse data, where null columns are not included in the document and a schema is included in the response of read to allow the client to rebuild the result. 

Dont think this has been implemented.

**Comment by hemidactylus** [comment]
I confirm the latest image `stargateio/data-api:v1.0.18` returns all columns (incl. nulls) at the moment.

**Comment by amorton** [comment]
@Yuqi-Du  when you do this, pls look at how the ReadAttempt creates the `projectionSchema` currently uses the columns on the driver result set. We want to change this to be the columns the projection wanted, because if we do an in memory sort we will read columns that were not requested by the user

**Comment by Yuqi-Du** [comment]
Fixed in https://github.com/stargate/data-api/pull/1633. 
This nullOption is originally included in this PR, Aaron wants to think on naming stuff, so separate out as an issue.
[https://github.com/stargate/data-api/issues/1636]
