### ISSUE TITLE
Reading from (unfrozen) MAP<text,...> errors out

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1575]
It seems that maps, the kind that the API would most like, cannot be read (1.0.18 on docker).

This was in the createTable payload:

```
...
                "p_map_text_text": {
                    "keyType": "text",
                    "type": "map",
                    "valueType": "text"
                },
...
```

This is the bit from CQL DESCRIBE TABLE:

```
...
    p_map_text_text map<text, text>,
...
```

This is what happens when trying a `find` on the table:

```
{
    "errors": [
        {
            "message": "Unsupported projection parameter: Column 'p_map_text_text' has unsupported type 'Map(TEXT => TEXT, not frozen)'",
            "errorCode": "UNSUPPORTED_PROJECTION_PARAM"
        }
    ]
}
```

to my understanding, this is the kind of map that the API should fully work with.

**Comment by tatu-at-datastax** [comment]
Need codec for `Map`s, #1451, one of 2 remaining codec issues to complete this week (along with #1493 for vectors).

**Comment by hemidactylus** [comment]
Thanks. I found another problem with $binary that seems codec-related and filed this: https://github.com/stargate/data-api/issues/1578

I don't want to spam with obvious issues, but you mentioned the "2 remaining codec issues" and this one seemed very much a new one to me. Feel free to close :|
