### ISSUE TITLE
(Tables) Cannot truncate a table (generated CQL has syntax errors)

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1577]
```
{
  "deleteMany": {
    "filter": {}
  }
}
```

yields (1.0.18)

```
{
    "errors": [
        {
            "message": "line 0:-1 mismatched input '<EOF>' expecting K_WHERE",
            "errorCode": "INVALID_QUERY"
        }
    ]
}
```

It looks like the CQL generation does not intercept the absence of predicates, hence it does not turn the CQL into a TRUNCATE statement at all.

**Comment by Yuqi-Du** [comment]
Thanks! We have it coming.
https://github.com/stargate/data-api/pull/1623
