### ISSUE TITLE
(tables) findOne with no matches returns a bare `{}` (v1.0.18)

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1580]
on Collections, if no matches, a findOne would return `{'data': {'document': null}}`.

Whereas, on Tables, in absence of matches the response is simply `{}` (hardly intentional IMO).

**Comment by amorton** [comment]
@hemidactylus I think we fixed this, can you confirm if this is still the case ?

**Comment by hemidactylus** [comment]
All good now indeed! I will close the issue
