### ISSUE TITLE
Add convenience methods for verifying whether map, set, list CQL type supported

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#1612]
(continuation of #1600 / #1451)

From @amorton : 

-----

we have this check for supported key types in a few places. Do you also have a check for supported value types ?
Do you have the same for the valueTypes for lists , sets, and vectors ?

if so can you put them public in places that make sense and I can call them from higher up when working out if we support the schema for a table

e.g. I have this in a PR for working out if we support the map schema for a table

    public static boolean isCqlTypeSupported(MapType cqlMapType) {
      Objects.requireNonNull(cqlMapType, "cqlMapType must not be null");

      // cannot be frozen
      if (cqlMapType.isFrozen()) {
        return false;
      }
      // keys must be text or ascii, because keys in JSON are string
      if (!(cqlMapType.getKeyType() == DataTypes.TEXT
          || cqlMapType.getKeyType() == DataTypes.ASCII)) {
        return false;
      }
      // must be a primitive type value
      return cqlMapType.getValueType() instanceof PrimitiveType;
    }

**Comment by amorton** [comment]
similar to #1568 and linked tickets there

**Comment by tatu-at-datastax** [comment]
I don't think this is a bug but proposed refactoring (although not sure how practical as written).

**Comment by amorton** [comment]
cosing as fixed in #1568
