### ISSUE TITLE
support includeSimilarity option for find and findOne for tables

### ISSUE THREAD

**Issue by amorton** [stargate/data-api#1634]
This is what the command looks like for collections

```json
{
    "find": {
        "sort" : {"$vectorize" : "Story about a person who can't sleep"},
        "projection":{"_id": 0, "$vector": 0, "$vectorize" : 1},
        "options" : {"limit" : 1, "includeSimilarity" : true}

    }
}
```

And it will return the `$similarity` field in the document. 

This is a CQL example:

```
cassandra@cqlsh:demo> select comment, similarity_cosine(comment_vector, [1.0, 1.0,1.0,1.0,1.0]) from vector_5;

 comment                          | system.similarity_cosine(comment_vector, [1.0, 1.0, 1.0, 1.0, 1.0])
----------------------------------+---------------------------------------------------------------------
 comment about cheese and monkeys |                                                             0.87512

(1 rows)
cassandra@cqlsh:demo> select comment, similarity_cosine(comment_vector, [1.0, 1.0,1.0,1.0,1.0]) as "foo" from vector_5;

 comment                          | foo
----------------------------------+---------
 comment about cheese and monkeys | 0.87512

(1 rows)
```

So we have a decision to make, when this happens with a table what do we do with the field in the result ? Do we:
1. Add a field to the document called `$similarity` like with collections, but that could mean there is a name collision 
2. Do the above by default, but also support an optional alias in by using `{"includeSimilarity" : "my_alias"}`

If we do 2 above then we also need to do this for collections as well. 

So we can implement 1 as the quick solution, and then split out 2 for a fast follow to be more table friendly.

**Comment by vkarpov15** [comment]
I'm supportive of `includeSimilarity: 'my_alias'`. Relying on `$similarity` is fine, but I think the `includeSimilarity: 'my_alias'` adds some useful flexibility.
