### ISSUE TITLE
alterTable with e.g. `"add": {}` gives a 500 Internal Server Error

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1681]
"Server failed: root cause: (java.lang.IllegalStateException) columnsToAdd must be non null and non empty.", while a graceful "regular" error is probably the right thing to do

**Comment by amorton** [comment]
fix: need to handle no operations and operations that a empty.

**Comment by amorton** [comment]
after discussion, while this is a fault in the API the clients will not generate requests like this so removing from the dec-hotfix , will only merge into main
