### ISSUE TITLE
(regression) countDocuments returns a count capped at 20 for collections

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1708]
Hello, I detected a regression with "countDocuments" on main (at least for collection). If more than 20 documents, the API returns a count of 20. By bisection, I identified the first commit where this was introduced: 59d6b0cb Fixes #1677 - page state returned (#1689)

**Comment by Yuqi-Du** [comment]
close, fixed by https://github.com/stargate/data-api/pull/1715
