### ISSUE TITLE
Insertion to Table SET and MAP columns does not necessarily preserve order

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1724]
(note: it should be verified that in C*, set and map collection columns are ordered (I think so, but must be double checked). Under this assumption...()

Insertion into such columns does not respect the order items are provided in the insert payload. E.g. for a set and a map:

```
"p_map_text_text":{"x":"YYY","p":"QQQ"},"p_set_int":[109,-43,0,111], ...
```

but then when reading (through Data API) I get

```
{-43, 0, 109, 111}, {"p":"QQQ", "x":"YYY"}
```

Also checking through CQL I can confirm the order on DB is the "wrong" one, i.e. those obtained when reading.

**Comment by vkarpov15** [comment]
Just checking this means if you insert fields `{ name: 'test', age: 42 }` as a map, you'll always get back the fields `name, age` in the original order? I tried to test this myself but ran into #1747
