### ISSUE TITLE
Table vectorize, different providers, different dimension, 500 Internal Server

### ISSUE THREAD

**Issue by Yuqi-Du** [stargate/data-api#1752]
Split from #1726.
Current ticket is for dec-hot-fix to solve.

### Two columns with same provider, model and dimension

Inserting a row with `{v1: "blabla", v2: [...]}` (i.e. one string and one vector) works

Both vectors: works

Both strings: works (two different embedding vectors got stored for two different texts, as expected)

### Two columns with same provider and model, but different dimension

Passing both as strings _does not work_: the API mistakenly thinks both vectors are the same dim:

```
The Embedding Provider returned an unexpected response: The Embedding Provider
returned an unexpected response: Embedding provider 'openai' did not return expected
embedding length. Expect: '333'. Actual: '123'
(EMBEDDING_PROVIDER_UNEXPECTED_RESPONSE)
```

### Two columns with same provider, different models, different dimensions

Same error as above (and I suspect at this point even if the dimension did match it would either error or work in the wrong way)

### Two columns with different providers

This time, inserting both as strings leads to a 500 Internal Server Error:

```
Server failed: root cause: (java.lang.IllegalArgumentException) Must be single
embedding provider name, got [openai, jinaAI]. Server error '500 Internal Server
Error' for url 'https://[...]-us-west-2.apps.astra-dev.datastax.com/[...]/<TABLE>
```

If one of the two is passed as a vector, instead, and the other is a string, depending on which one two things happen:

1. it works
2. the dimension-mismatch error seen above is triggered (probably because the dimension is still a table-level setting somewhere and is used for the wrong model)

**Comment by amorton** [comment]
this was merged into https://github.com/stargate/data-api/tree/feature/dec-hotfix 

closing, will start a task to support any combination of provider, model, and dimensions in the new year.
