### ISSUE TITLE
JinaAI V3 model has wrong default dimension and unclear help text

### ISSUE THREAD

**Issue by Hazel-Datastax** [stargate/data-api#1766]
1. The model has dimension defaults to 1536 but has a [1, 1024] validation
2. Unclear help text of `task` of what options are available

**Comment by amorton** [comment]
on hold for hotfix until we work out if jina is in hotfix

**Comment by amorton** [comment]
putting on hold until we know 

1. should we change the default or change the range tests ? 
2. what the new help text shoud be
