### ISSUE TITLE
"Collection does not exist" error wording should -> Collection/Table

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1769]
Running e.g. a findOne against an URL with a nonexisting "collection-or-table" gives an error message that implies this would be a collection. The wording should become agnostic.

Repro: issue a request such as

```
{
    "findOne": {
        "filter": {}
    }
}
```

to an URL such as (note the made-up last bit: `mimmo` is not a table nor a collection)

```
{{DATA_API_ENDPOINT}}{{DATA_API_CONTEXT_PATH}}/v1/{{DATA_API_KEYSPACE}}/mimmo
```

The error is now:

```
{
    "errors": [
        {
            "message": "Collection does not exist, collection name: mimmo",
            "errorCode": "COLLECTION_NOT_EXIST",
            "id": "9730a4a9-4bd6-4235-9e6b-b04d3544ceca",
            "title": "Collection does not exist, collection name",
            "family": "REQUEST",
            "scope": "EMPTY"
        }
    ]
}
```

**Comment by amorton** [comment]
closing, we will fix as part of #1791 the code in these classes needs to be refactored
