### ISSUE TITLE
Limit number of documents to count

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/data-api#431]
During some initial performance testing we determined that the `countDocuments` operation can be quite expensive on collections with large numbers of documents. 

While we do see some improvement in the resources used by this operation due to the fix in #427, there are limits in how well this can perform due to the nature of how the CQL COUNT operation works.

We should add a configurable limit on the number of docs that will be counted in a countDocuments operation, along the lines of other operation limits documented at https://github.com/stargate/jsonapi/blob/main/CONFIGURATION.md#operations-configuration. This could then be enforced by adding a LIMIT clause to the SELECT COUNT query with the configured value.

**Comment by tatu-at-datastax** [comment]
Does `LIMIT` work on `SELECT COUNT`? It seems that this was not the case at some point at least:

https://stackoverflow.com/questions/36174805/cassandra-cql-select-count-with-limit

but it's confusing as there's claim problem was fixed:

https://issues.apache.org/jira/browse/CASSANDRA-18150

However, from Astra cqlsh it appears that LIMIT is not obeyed in this way -- full count is returned.

**Comment by jeffreyscarpenter** [comment]
@tatu-at-datastax you are correct, rereading the links you selected, the LIMIT clause has no practical effect since the count() operation only returns 1 row. Closing this issue.
