### ISSUE TITLE
Run JSON API with DSE 7

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/data-api#600]
There are now Docker images being published for DataStax Enterprise 7 on [Docker Hub](https://hub.docker.com/layers/datastax/dse-server/7.0.0-alpha.1/images/sha256-d97e7ae7110e7ff367be8976fc3b6237bddf155e8f99c9ad7ec2c9a61954bca6?context=explore).

Since DSE 7 is based on https://github.com/datastax/cassandra, most SAI features required by JSON API are available or will be available soon. We can start exploring DSE 7 support as an experimental feature.

**Comment by jeffreyscarpenter** [comment]
Since JSON API has been converted to CQL, it could probably connect directly to a Cassandra node with support for SAI features we need. 

We could try this first with dse-next in a docker compose configuration, will probably just require getting username/password set on Cassandra connection. 

Next we could update the IT framework `StargateTestResource` to omit coordinator. 

Finally, when we confirm latest SAI changes are available in DSE 7, could add support in docker compose and IT framework.

Thoughts @maheshrajamani @tatu-at-datastax?

**Comment by tatu-at-datastax** [comment]
I guess one clarifying question is whether we are thinking of dropping Coordinator out of production deployment or not? To me, ITs and local Docker compose should be close to Production set up so we see as similar behavior as possible. So although I can see benefits of not having to provide Coordinator/Persistence, I think we should not fragment our deployments -- as that would ideally require now testing 2 different set ups, for all changes.

So: are we thinking of dropping the whole idea of Coordinators (no-data nodes) in near future? If so, yes, this would make sense. If not, I think it would actually add complexity, not reduce it.

**Comment by jeffreyscarpenter** [comment]
Let's simplify this a bit for now. For this particular issue, let's create an additional docker-compose configuration that runs JSON API in front of a single DSE 7 node, with no coordinator, and see what we need to do to make that work. We will probably want to have JSON API use Cassandra username/password to connect to the DSE node. 

Since it is somewhat likely that we will have to create a new persistence module in order to have a DSE 7-compatible coordinator, I'll create an issue for that in the main Stargate repo.
