### ISSUE TITLE
Remove dependency for Stargate bridge - quarkus commons

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/data-api#673]
Now that json api is directly using cql driver. Remove the dependency for qstargate quarkus commons.

**Comment by jeffreyscarpenter** [comment]
After internal discussion, we're going to refine/clarify the scope a bit and update the title of this issue. There are still some useful capabilities in the quarkus commons such as the metrics classes, we don't intend to remove those at this time. 

The main intent is to eliminate dependence on the "bridge". This has been completed for the most part with the transition to using the driver CQL in #606 and other PRs. The API no longer communicates to Stargate coordinator nodes via the gRPC bridge, but there are a couple of small references and dependencies remaining, including:

- references to properties such as `quarkus.grpc.clients.bridge.host`, `quarkus.grpc.clients.bridge.port`, and `stargate.data-store.ignore-bridge` properties in Java code, docker compose files, and helm charts. This is 
- usage of the sgv2-quarkus-commons `QueryBuilder`, which is heavily tied to the `Values` classes from the gRPC bridge protos. Replacement with the Java Driver's query builder is recommended, although we need to verify that it handles the new vector type. 

The two sets of changes identified above should likely be made in separate PRs.
