### ISSUE TITLE
Wording of timeout error message

### ISSUE THREAD

**Issue by johnsmartco** [stargate/data-api#743]
Hey guys - this idea might be a duplicate of existing work. Ignore and close this one, if that's the case.

Our beta5 timeout error response is:

{"errors":[{"message":"Query timed out after PT20S"}]}

How about:

{"errors":[{"message":"Query timed out after 20 seconds"}]}

?

**Comment by tatu-at-datastax** [comment]
I couldn't immediately see code that we'd have to create error message, so I suspect this is something created by another component (like Java Cassandra Client or CQL Proxy). So it might not be easy to try to change this.

One thing to note is that while `PT20S` is not very user-friendly, it is (I think) an ISO-8601 format for time Periods so somewhat standard notation.

Will leave issue open in case we figure out if it is possible to change the exception message for more human-readable.

**Comment by vkarpov15** [comment]
You're right about PT20S being a valid ISO-8601 format for time periods, [here's some more info](https://tc39.es/proposal-temporal/docs/duration.html#:~:text=Briefly%2C%20the%20ISO%208601%20notation,zero%20components%20may%20be%20omitted.). While this notation is standard, I can genuinely say I have never heard of this notation or seen it in the field before.

Is there any concrete advantage to using PT20S versus 20 seconds? I would imagine PT20S is easier to write a parser for, but I don't think that's a common use case for error messages. My suggestion would be to use 20 seconds over PT20S unless there's some strong reason to use PT20S.

**Comment by tatu-at-datastax** [comment]
I don't think there are many benefits, except maybe for that being likely value used in configuration settings.
So for developers (us :) ) might be bit easier to see where configuration comes from.

But the concern I have is that we don't control code that produces the exception (we didn't create this message) so changing it is more difficult, that's all.
