### ISSUE TITLE
Request: full docker example

### ISSUE THREAD

**Issue by 7flash** [stargate/data-api#753]
Adding docker-compose with cassandra 5.0 instance included,

It would be useful to have single-click deployment to railway

**Comment by jeffreyscarpenter** [comment]
The Data API relies on improvements to Storage-attached Indexes (SAI) that are currently only available in https://github.com/datastax/cassandra/tree/vsearch. This is why our test code and docker compose scripts reference something called "dse-next" persistence. The docker compose scripts were not working for a time but have recently been fixed under https://github.com/stargate/data-api/pull/864
