### ISSUE TITLE
Add Metrics for in-flight commands (Gauge on `MeteredCommandProcessor`)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#854]
It would be useful to know number of concurrently processed commands (~= in-flight requests), in addition to rates and timing of commands. This would, for example, let us see if specific slow-executing (and possibly timing out) commands might temporary pile up (since it takes long for them to be executed).
This would be simple to add in `MeteredCommandProcessor`, as a gauge-type metrics: increase before processing, decrease after (regardless of whether successful or not). Tags should only include command name and not much else (cannot refer to anything not available at time before starting; per-tenant break-down does seem as useful although that could be considered).

**Comment by jeffreyscarpenter** [comment]
We have other diagnostics we should use in favor of this (for example, thread state metrics)

**Comment by tatu-at-datastax** [comment]
I don't think those are quite the same are they? Thread-state may have real-time information on command it is running on, but would not be reported as historical data.

We might still consider these metrics as long as they are not per-tenant since gauges are low-cardinality (we'd have 1 metric per Command).
And could be quite useful for troubleshooting after the fact, observing pile-up of specific command during overload situations.
