### ISSUE TITLE
Change path-name convention shredder uses to be same as needed by filtering (no need to de-shred)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#91]
Originally super-shredder path names were thought to be needed to allow "de-shredding" -- re-building of the source document from shredded paths.  This is why path to value '5' in:

```json
{ "array" : [ 5 ] }
```

would become `array.[0]`, escaped so that path is never ambiguous, even if property name contained `.` (allowed in later Mongo versions) or opening bracket (likewise legal).

But Mongo filtering clauses use simpler, potentially ambiguous notation: `array.0`.

Although we could of course convert from `array.0` into `array.[0]` it makes more sense to simplify shredded paths because:

1. There is no need to "de-shred" (we store the full document)
2. Avoiding conversion is not only more efficient but also removes possible error modes.

**Comment by amorton** [comment]
> Question to explore is can SAI index search of wild card for map key, if so we may not need the array_contains.
> Like query_xxx_values['array.*] = 5
> @amorton Can we check if this is a possibility?

It would not be possible, maybe something to add later if / when we create a full JSON type in C*
