### ISSUE TITLE
Define acceptable consistency levels set globally

### ISSUE THREAD

**Issue by ivansenic** [stargate/data-api#94]
@amorton mentioned that due to the Light-Weight-Transactions we need to use specific global consistency levels. Currently those are picked from `sgv2-quarkus-common` and are:

```
stargate.queries.consistency.reads=LOCAL_QUORUM
stargate.queries.consistency.writes=LOCAL_QUORUM
stargate.queries.consistency.schema-changes=LOCAL_QUORUM
```
We should add a start-up checker that ensures that setup consistencies are fine with the LWT approach. See https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/dml/dmlLtwtTransactions.html

**Comment by jeffreyscarpenter** [comment]
Verified that we [default](https://github.com/stargate/data-api/blob/1f73c065401105df2f38e5b27ced600d0383488a/src/main/java/io/stargate/sgv2/jsonapi/config/OperationsConfig.java#L222) the serial consistency level to LOCAL_SERIAL, closing.
