### ISSUE TITLE
Java driver ServerError on multiple operations

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/data-api#946]
From logs and metrics data, there are instances where the API returns Java driver ServerError to the user instead of catching and mapping to a better exception message. 

For example, the following stack trace has been observed on Insert operations:

```
com.datastax.oss.driver.api.core.servererrors.ServerError: java.lang.IllegalArgumentException: Cannot find table, it may have been dropped.
```

The following was observed on an update:

```
com.datastax.oss.driver.api.core.servererrors.ServerError: Router is unable to retry non-idempotent query after connection to backend cluster closed
```

And the following on a DeleteCollection:

```
com.datastax.oss.driver.api.core.servererrors.ServerError: Failed to connect upstream session
```

It's possible that many or most of these are timing issues that are related to collections (tables) or databases being deleted. We may want to think about adding appropriate retries, and possibly we should include warning messages in the response body rather than treating as a 500 server error.

**Comment by Hazel-Datastax** [comment]
The first error seems to have happened when the DB was moved between shared and dedicated resources and it seems solved by the CNDB team https://github.com/riptano/cndb/issues/7381. Not sure if it works now. What error message should we use if we get this server again?

**Comment by Hazel-Datastax** [comment]
Regarding the second error, I found a similar [incident](https://datastax.slack.com/archives/C05T0HJAUCE/p1708015962752749) and it seemed related to the DB scaling problem. But our error message starts with `Router`, does it indicate it may also related to the cql router?

**Comment by Hazel-Datastax** [comment]
For the third one, I could not find the error that happened recently in deleteCollection, but found
```
[s9511] Unexpected error while refreshing schema after a successful reconnection, keeping previous version (CompletionException: com.datastax.oss.driver.internal.core.adminrequest.UnexpectedResponseException: query 'SELECT * FROM system_schema.keyspaces' got unexpected response ERROR(Failed to connect upstream session))
```
```
[s3855] Unexpected error while refreshing schema during initialization, proceeding without schema metadata (CompletionException: com.datastax.oss.driver.internal.core.adminrequest.UnexpectedResponseException: query 'SELECT * FROM system_schema.keyspaces' got unexpected response ERROR(Failed to connect upstream session))
```
